"""Pydantic schemas for LLM structured output (Phase 3).

Unlike the dataclasses in ``app/models/schemas.py`` (which describe data
*we* produced from trusted sources), the models here validate data
**generated by an LLM** — external, untrusted input that must be checked at
runtime before the rest of the project may rely on it. That is why this
module uses Pydantic v2 while earlier phases could stay on plain dataclasses.

First schema: :class:`SearchIntent`, the extraction result of a user's
natural-language research goal. It is deliberately minimal — only what the
user's text itself can support. No pathways, PMIDs, gene functions or
evidence: the user text contains none, so the model must not invent them.
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, field_validator

#: Hard cap on cleaned topics per intent (keeps prompts/queries bounded).
MAX_TOPICS = 10


class SearchIntent(BaseModel):
    """A literature-search intent extracted from user text.

    Fields:
        gene: gene symbol exactly as written by the user — stripped,
            non-empty, casing preserved (``Trp53`` stays ``Trp53``). NOT
            validated against any gene database (Phase 3 has none).
        disease: disease / context explicitly mentioned by the user;
            ``None`` when absent or blank. NOT looked up in any ontology.
        topics: research aspects explicitly mentioned (mechanisms,
            methods, …); cleaned (stripped, empties dropped, de-duplicated
            in first-seen order), at most :data:`MAX_TOPICS` after
            cleaning; flat strings only (nested structures rejected).

    Unknown/extra fields are rejected (``extra="forbid"``): the system
    prompt forbids the model from adding fields (pathway, pmid, …), and a
    loud validation error keeps that violation observable instead of
    silently dropping data.
    """

    model_config = ConfigDict(extra="forbid")

    gene: str
    disease: str | None = None
    topics: list[str] = []

    @field_validator("gene")
    @classmethod
    def _clean_gene(cls, value: str) -> str:
        gene = value.strip()
        if not gene:
            raise ValueError("gene must be a non-empty string after stripping")
        return gene  # casing intentionally preserved

    @field_validator("disease")
    @classmethod
    def _clean_disease(cls, value: str | None) -> str | None:
        if value is None:
            return None
        return value.strip() or None  # "" -> None

    @field_validator("topics")
    @classmethod
    def _clean_topics(cls, value: list[str]) -> list[str]:
        cleaned: list[str] = []
        for topic in value:
            text = topic.strip()
            if text and text not in cleaned:  # drop empties, keep first occurrence
                cleaned.append(text)
        if len(cleaned) > MAX_TOPICS:
            raise ValueError(
                f"topics must contain at most {MAX_TOPICS} entries after "
                f"cleaning, got {len(cleaned)}"
            )
        return cleaned
